version: '3.8'
services: 
  webapp: 
    build: .
    image: meu-app-compose:v1.0
    ports: 
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  redis:
    image: "redis:alpine"